install_dir=${HOME}/.local/bin

.PHONY: install
install:
	@[ -d ${install_dir} ] || mkdir -p ${install_dir}
	@cp ./mkmake.py ${install_dir}/mkmake
	@chmod 0744 ${install_dir}/mkmake	


## test:  Test of Makefile generated by the script
.PHONY: test
test:
	./mkmake.py -dP "NAME update DESC Updates the system (super user privileges required). REQ confirm STEP @echo Updating system... STEP @sudo apt -y update && echo System updated"
